name: GitHub Pages

on:
  push:
    branches:
      - "main"

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: cache poetry
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry

      - name: install poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: curl -sSL https://install.python-poetry.org/ | python3 -

      - name: add poetry to path
        run: echo "{HOME}/.local/bin" >> $GITHUB_PATH

      - name: dependencies cache
        uses: actions/cache@v2
        id: dependencies-cache
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetrydependencies-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetrydependencies-

      - name: install dependencies
        run: poetry install --no-interaction

      - name: Build
        run: make sphinx

      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
